version: '3'
services:
  bot:
    build: .
    environment:
      - BOT_TOKEN_API=${BOT_TOKEN_API}
      - HOST=${HOST}
      - DB=${DB}
      - USER=${USER}
      - PASSWORD=${PASSWORD}
    restart: always